### ISSUE TITLE
How do you train on imagenet? 

### ISSUE THREAD

**Issue by Coderx7** [D-X-Y/ResNeXt-DenseNet#11]
Hi, first of all thank you very much for this great work of yours. 
I tried to use the imagenet_train.py to train couple of models on imagenet. However, at the very beginning I face this error : 
```
    ....
    (42): ReLU(inplace)
  )
  (classifier): Linear(in_features=432, out_features=1000, bias=True)
)
=> parameter : Namespace(arch='simp_imgnet_5m_nop_safc_s1', batch_size=256, data='/media/hossein/DataSection/DeepLearning/ImageNet_DataSet', epochs=100, evaluate=False, lr=0.1, momentum=0.9, prefix='2018-05-01-1457', print_freq=200, resume='', save_dir='./snapshots/simp/', start_epoch=0, train_dir_name='training_set_t12/', val_dir_name='imagenet_val/', weight_decay=0.0001, workers=16)
/home/hossein/anaconda3/lib/python3.6/site-packages/torchvision/transforms/transforms.py:397: UserWarning: The use of the transforms.RandomSizedCrop transform is deprecated, please use transforms.RandomResizedCrop instead.
  "please use transforms.RandomResizedCrop instead.")
/home/hossein/anaconda3/lib/python3.6/site-packages/torchvision/transforms/transforms.py:156: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
Traceback (most recent call last):
  File "imagenet_train.py", line 304, in <module>
    main()
  File "imagenet_train.py", line 116, in main
    normalize,
  File "/home/hossein/anaconda3/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 103, in __init__
    "Supported image extensions are: " + ",".join(IMG_EXTENSIONS)))
RuntimeError: Found 0 images in subfolders of: /media/hossein/DataSection/DeepLearning/ImageNet_DataSet/imagenet_val/
Supported image extensions are: .jpg,.jpeg,.png,.ppm,.bmp,.pgm

```
 The path is correct, however, all image extensions in the respective folders are `.JPEG` and I guess this is the reason the error is being thrown. This is the default ImageNet dataset and I have not meddled with it. So how did you get around this issue?

**Comment by D-X-Y** [comment]
Hi, I check my data, the image extension is also JPEG.
I think it is because the folders in your ImageNet_DataSet is not right?
In my ILSVRC2012 folder, there are two sub-folders 'train' and 'val'. In these two sub-folders, there are 1000 sub-folders representing each the ImageNet-1000 classes. The images are in these 1000 sub-folders.

**Comment by Coderx7** [comment]
Thank you very much. 
its weird ! the training subfolder is like what you described, there are subfolders for each class(1000). However, the validation subfolder contains only 50K images. 
I downloaded the whole ILSVRC2012 from the main ImageNet site back in 2016!

**Comment by D-X-Y** [comment]
@Coderx7 
I update the README, you can follow the instruction to organize your validation data.
