### ISSUE TITLE
Wrong checksum for the ILSVRC12_img_val ? 

### ISSUE THREAD

**Issue by Coderx7** [D-X-Y/ResNeXt-DenseNet#13]
Hi, 
Thanks a lot for the quick instruction on preprocessing validation data for imagenet. However, I just checked the md5 checksum and noticed your checksum does not align with the original ILSCRC12_img_val checksums : 
`Validation images (all tasks). 6.3GB. MD5: 29b22e2961454d5413ddabcf34fc5622`

**Comment by D-X-Y** [comment]
I just delete that line, that MD5 is for a compressed file containing both train and val, you can ignore that.
