### ISSUE TITLE
A question concerning the preprocessing operation on imagenet_training.y

### ISSUE THREAD

**Issue by Coderx7** [D-X-Y/ResNeXt-DenseNet#16]
Hi @D-X-Y , 
Should you not rescale the training samples and then take 224x224 crops ? 
so far we have : 
```
    train_dataset = datasets.ImageFolder(
        traindir,
        transforms.Compose([
            transforms.RandomSizedCrop(224),
            transforms.RandomHorizontalFlip(),
            transforms.ToTensor(),
            normalize,
        ]))
```

but shouldn't we have  `transforms.Scale(256)` here as well? 
we do rescale the images for validation, 
 ```
   val_loader = torch.utils.data.DataLoader(
        datasets.ImageFolder(valdir, transforms.Compose([
            transforms.Scale(256),
            transforms.CenterCrop(224),
            transforms.ToTensor(),
            normalize,
        ])),
```
wich is right. but what about the training ? 
Thank you in advance

**Comment by D-X-Y** [comment]
Please refer to https://github.com/facebook/fb.resnet.torch , RandomSizedCrop is a kind of data argumentation which outperforms Scale+Crop.

**Comment by Coderx7** [comment]
@D-X-Y : My apologies, I missed that _Sized_ part and thought that's a random crop operation! 
but I can't find any documentation concerning that, it seems it's been replaced by the newer version : [RandomResizedCrop ](https://pytorch.org/docs/master/torchvision/transforms.html#torchvision.transforms.RandomResizedCrop) are they essentially the same? 
Actually, I was just looking at it and the new method resembles the one in the link you just posted. I wonder if these two are the actually same! (knowing that the RandomSizedCrop is deprecated now)
Again thank you a gazillion times :)
