### ISSUE TITLE
Write failed: Broken pipe

### ISSUE THREAD

**Issue by ZhangLeUestc** [D-X-Y/ResNeXt-DenseNet#17]
Hi, 

The program was shut down and throw out an error ``Write failed: Broken pipe" when I was training imagnet using the cmd: CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 sh ./scripts/train_imagenet.sh resnet18

I tried several suggestions after a google search and none of them helped out.  

I am using ubuntu16.04 with 8 1080 GPU cards.  I  set num_work=0 and 1 to disable multi-thread as suggested here: https://github.com/pytorch/pytorch/issues/2341
I also tried to wrap all operations in functions and then call them inside an if __name__ == '__main__' as suggested here: https://discuss.pytorch.org/t/brokenpipeerror-errno-32-broken-pipe-when-i-run-cifar10-tutorial-py/6224/4?u=karmus89.

Has anyone encountered the same problem? Thank you so much.

**Comment by D-X-Y** [comment]
Please give more information, e.g., error log

**Comment by ZhangLeUestc** [comment]
Hi D-X-Y，

Thanks for the prompt reply!

![1525762498 1](https://user-images.githubusercontent.com/20219832/39742447-11954dcc-52d0-11e8-9d75-1bbaba98d1e3.jpg)
Hi, plz see the screen-shot.  Can not trace the error from the log.
And there do exist enough memory.
![1525762734](https://user-images.githubusercontent.com/20219832/39742568-926468ca-52d0-11e8-9b53-e7425abc540e.jpg)

**Comment by D-X-Y** [comment]
It is weird. Is the code ok when running on a single GPU?

**Comment by ZhangLeUestc** [comment]
Not Ok.

**Comment by saeedizadi** [comment]
The exact same problem here. Any update on this?

**Comment by D-X-Y** [comment]
I suggest you try another repo: https://github.com/D-X-Y/NAS-Projects, where the codes are upgraded and some pre-trained models are provided.
