### ISSUE TITLE
mean = [x / 255 for x in [125.3, 123.0, 113.9]] std = [x / 255 for x in [63.0, 62.1, 66.7]]  what's the meaning of these number?

### ISSUE THREAD

**Issue by hmyan90** [D-X-Y/ResNeXt-DenseNet#18]
mean = [x / 255 for x in [125.3, 123.0, 113.9]] std = [x / 255 for x in [63.0, 62.1, 66.7]] what's the meaning of these number?

**Comment by hmyan90** [comment]
mean = [x / 255 for x in [125.3, 123.0, 113.9]]
std = [x / 255 for x in [63.0, 62.1, 66.7]]

what's the meaning of these number?

**Comment by D-X-Y** [comment]
See Facebook implementation : https://github.com/facebook/fb.resnet.torch/blob/master/datasets/cifar10.lua
