### ISSUE TITLE
MobileNetv1 and v2 results

### ISSUE THREAD

**Issue by Coderx7** [D-X-Y/ResNeXt-DenseNet#20]
Hi, Would it be possible for you to also add MobileNets([V1](https://github.com/marvis/pytorch-mobilenet), [V2](https://github.com/Randl/MobileNetV2-pytorch)) to your experiment? 
Would that be possible? 
Thanks a lot in advance

**Comment by D-X-Y** [comment]
Hi, you can refer this project : https://github.com/tonylins/pytorch-mobilenet-v2
