### ISSUE TITLE
Question about performance of ResNet model on the ImageNet dataset

### ISSUE THREAD

**Issue by chunfuchen** [D-X-Y/ResNeXt-DenseNet#3]
Hi, 
I am curious do you have results on ResNet model on the ImageNet dataset? like ResNet18, ResNet50 or others. If so, do you mind sharing trained models?

I used your codes to train a ResNet18 and it achieved ~29.5% top-1 validation error, which is good.

Nonetheless, its top-1 training error only achieved ~30.6%, which is weird, since in my understanding, the training error should be smaller than validation error. (This training error is the average error over entire training set)

Not only for ResNet18, I see the same pattern on ResNet50 when I trained from scratch. 

Do you have any idea why the validation error is lower than training error?

Thanks.

**Comment by D-X-Y** [comment]
hi, I have trained the ResNet-152 and ResNet-101 using this code, the results are lower than the official PyTorch pre-trained models by about 0.4%. 
https://github.com/pytorch/vision/blob/master/torchvision/models/__init__.py
I didn't save the results. I will check it, but it needs some time

**Comment by chunfuchen** [comment]
Hi, 
I am training a ResNet-152 and ResNet-50, and my ResNet-50 (@epoch 83) achieves 23.806% top-1 validation error, which is slightly better than official pre-trained model.

**Comment by D-X-Y** [comment]
Yes, compare to the official paper, the result is good. If compare to the Facebook torch code, the result is slightly lower. Maybe caused by data argumentation

**Comment by chunfuchen** [comment]
Please correct correct me if I am wrong, for ResNet-50, the result on the paper is 24.7% top-1 error, the result FB reproduced is 24.0% top-1 error. (http://torch.ch/blog/2016/02/04/resnets.html)

Thus, it seems that my trainning is slightly better than FB torch code? (the top-1 error achieves 23.5% @ epoch 98)

**Comment by D-X-Y** [comment]
Aaa, my mistake, 23.5% is better~
