### ISSUE TITLE
ResNeXt pre-trained imagenet

### ISSUE THREAD

**Issue by mrlzla** [D-X-Y/ResNeXt-DenseNet#6]
Hi. Awesome repo. Could you provide ResNeXt imagenet trained weights?)

**Comment by D-X-Y** [comment]
Sorry for that, we don't keep the ResNeXt pre-trained model. I would suggest converting the official ResNeXt model https://github.com/facebookresearch/ResNeXt to the PyTorch version by using https://github.com/clcarwin/convert_torch_to_pytorch
