### ISSUE TITLE
Hyper-parameters for other datasets

### ISSUE THREAD

**Issue by ZhangLeUestc** [D-X-Y/ResNeXt-DenseNet#9]
Hi,
Thanks for sharing this nice implementation.  But could you please provide the script/hyperparameters to train the other datasets (e.g, cifat100 and Imagenet) as well?

**Comment by D-X-Y** [comment]
Hi,
I updated the script files, the hyper-parameters for cifar-100 are the same with that of cifar-10. For ImageNet, I create a new script https://github.com/D-X-Y/ResNeXt-DenseNet/blob/master/scripts/train_imagenet.sh
